config/routes.rb
Rails.application.routes.draw do
  resources :books do
    member do
      get 'read'
      patch 'update_current_page'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :pdf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'read', only: [:read]

  before_action :set_book, only: %i[show edit update destroy read]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/1/read
  def read; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /books/1/update_current_page
  def update_current_page
    @book = Book.find(params[:id])
    new_current_page = params[:current_page].to_i

    if @book.update(current_page: new_current_page)
      head :no_content
    else
      render json: { errors: @book.errors }, status: :unprocessable_entity
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :description, :pdf)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= book.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= book.author %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= book.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Current page:</strong>
    <%= book.current_page %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this book", book, class: "rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
    <%= link_to 'Read this book', read_book_path(book), class: "rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
    <%= link_to 'Edit this book', edit_book_path(book), class: "rounded-lg py-3 ml-2 px-5 border border-gray-200 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "contents") do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :pdf %>
    <%= form.file_field :pdf, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing book</h1>

  <%= render "form", book: @book %>

  <%= link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
  <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Books</h1>
    <%= link_to 'New book', new_book_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="books" class="min-w-full">
    <%= render @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New book</h1>

  <%= render "form", book: @book %>

  <%= link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
</div>

app/views/books/read.html.erb
<div data-controller="pdf-reader" data-pdf-reader-url-value="<%= url_for(@book.pdf) %>" data-pdf-reader-book-id="<%= @book.id %>" data-pdf-reader-current-page="<%= @book.current_page %>">
  <div class="bg-gray-700 grid sticky top-0">
    <div class="justify-self-center">
      <button data-action="click->pdf-reader#prevPage">Previous page</button>
      <input type="number" min="1" data-pdf-reader-target="pageNumber" data-action="change->pdf-reader#changePage" class="shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2"/>
      <button data-action="click->pdf-reader#nextPage">Next page</button>
    </div>
    <div class="justify-self-center">
      <button data-action="click->pdf-reader#zoomIn">Zoom In</button>
      <button data-action="click->pdf-reader#zoomOut">Zoom Out</button>
    </div>
  </div>
  <p class="my-5">
    <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
    <strong class="block font-medium mb-1"><%= @book.title %></strong>
  </p>
  <div class="grid pb-20">
    <div class="justify-self-center">
      <canvas data-pdf-reader-target="canvas"></canvas>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @book %>

    <%= link_to 'Edit this book', edit_book_path(@book), class: "mt-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
    <%= link_to 'Read this book', read_book_path(@book), class: "mt-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "mt-2 rounded-lg py-3 px-5 border border-gray-200 font-medium" %>
    </div>
    <%= link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 border border-gray-200 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocReadHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-8 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/read.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocReadHub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="dark">
    <main class="container mx-auto mt-8 px-5">
      <%= yield %>
    </main>
  </body>
</html>